// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("OpenTK.TypeProviders.Runtime")>]
[<assembly: AssemblyProductAttribute("OpenTK.TypeProviders")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing OpenTK.TypeProviders.")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "OpenTK.TypeProviders.Runtime"
    let [<Literal>] AssemblyProduct = "OpenTK.TypeProviders"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing OpenTK.TypeProviders."
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
