// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("OpenTK.TypeProviders.DesignTime")>]
[<assembly: AssemblyProductAttribute("OpenTK.TypeProviders")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing OpenTK.TypeProviders.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "OpenTK.TypeProviders.DesignTime"
    let [<Literal>] AssemblyProduct = "OpenTK.TypeProviders"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing OpenTK.TypeProviders."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
